<a href="https://colab.research.google.com/github/Pranjulchaurasiya/DataAnalyticsLab/blob/main/DALAB_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
# Input matrix size
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

print("Enter elements of Matrix A:")
A = []
for i in range(rows):
    row = list(map(int, input().split()))
    A.append(row)

print("Enter elements of Matrix B:")
B = []
for i in range(rows):
    row = list(map(int, input().split()))
    B.append(row)

A = np.array(A)
B = np.array(B)

print("\nMatrix A:\n", A)
print("Matrix B:\n", B)



Enter number of rows: 2
Enter number of columns: 3
Enter elements of Matrix A:
1 4 6 
2 3 5
Enter elements of Matrix B:
1 3 5 
2 4 6

Matrix A:
 [[1 4 6]
 [2 3 5]]
Matrix B:
 [[1 3 5]
 [2 4 6]]


In [4]:
# Addition & Subtraction
if A.shape == B.shape:
    print("\nAddition:\n", A + B)
    print("\nSubtraction:\n", A - B)
else:
    print("\nAddition/Subtraction not possible")

# Multiplication
if A.shape[1] == B.shape[0]:
    print("\nMultiplication:\n", np.dot(A, B))
else:
    print("\nMultiplication not possible")

# Transpose
print("\nTranspose of A:\n", A.T)

# Inverse
if rows == cols:
    if np.linalg.det(A) != 0:
        print("\nInverse of A:\n", np.linalg.inv(A))
    else:
        print("\nInverse not possible (determinant = 0)")
else:
    print("\nInverse not possible (not a square matrix)")


Addition:
 [[ 2  7 11]
 [ 4  7 11]]

Subtraction:
 [[ 0  1  1]
 [ 0 -1 -1]]

Multiplication not possible

Transpose of A:
 [[1 2]
 [4 3]
 [6 5]]

Inverse not possible (not a square matrix)
